### ISSUE TITLE
not receiving message approval requests

### ISSUE THREAD

**Issue by Pawsitiveimprovements** [kevin-wynn/fifthbot-issues#3]
### Prerequisites

- [ ] Is this issue reproducible on the current live version?
- [ ] Does this issue expose security risks?
- [ ] Do you get any errors from the app? 

### Description

[Description of the bug or feature] not able to approve or deny anonymous messages. able to type /fifthbot hi. I receive the proper automatic message stating pending approval from admin to post the message. Admin never receives the message. I am the main admin and I have appointed 1 moderator. neither one of us receive any messages to approve/deny and anonymous message. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen] admin user is supposed to received approval/deny for all anonymous messages to be posted

**Actual behavior:** [What actually happened] receive a message stating waiting for approval from admin, but no message ever appears for admin.

**Comment by kevin-wynn** [comment]
@Pawsitiveimprovements I will take a look at this today and see if I can uncover whats happening and get it resolved!

**Comment by kevin-wynn** [comment]
Can you tell me what you get when you type `/fifthbot /moderator list`?

**Comment by Pawsitiveimprovements** [comment]
Here is the message I receive

**Comment by kevin-wynn** [comment]
I'm not seeing anything

**Comment by Pawsitiveimprovements** [comment]
It just states the team moderator is me (@Krista Lazo) when I type /fifthbot /moderator list

**Comment by kevin-wynn** [comment]
Okay, that helps! I am seeing an error in my logs with some details around your team. This will help me find the bug and get this sorted out. I'll hopefully have this resolved by tonight!

**Comment by Pawsitiveimprovements** [comment]
Awesome! Thanks! I really appreciate your help

**Comment by kevin-wynn** [comment]
I pushed up a possible fix with some more logging around the area that was possibly failing. So if it doesnt work when you try it next I will have more data to go on, but if it works then my assumption was right.

Let me know if this fails again for you next time you try it!

**Comment by Pawsitiveimprovements** [comment]
Hi! It's still not working. This is what I am seeing...Slackbot [9:42 PM] */fifthbot hi, how are u?* failed with the error “operation_timeout"

Thanks!

**Comment by kevin-wynn** [comment]
I am seeing the error come across from slack with a bad auth token. Could you try re-installing the app into your slack org?

**Comment by Pawsitiveimprovements** [comment]
I deleted the app and re installed it. I am still receiving the same error :/

**Comment by kevin-wynn** [comment]
there may be a bug in my re-auth code. im going to remove your auth key and have it force you to re-auth when you try to reinstall

**Comment by Pawsitiveimprovements** [comment]
Ok let me know when you are ready for me to delete and reinstall the app again.

**Comment by kevin-wynn** [comment]
You should be good to try again now. If it fails with a new install I might have to push up some of the new updates I've been working on sooner rather than later

**Comment by Pawsitiveimprovements** [comment]
Yay it worked!!! I am so grateful!!! Thank you so much!

**Comment by kevin-wynn** [comment]
Thats good to hear! I'll file a bug report on the private repo to look into my auth flow and make sure there are no bugs there that can cause this again. Thank you for reporting!
